---
apiVersion: v1
kind: Service
metadata:
  name: kube-jwt-authn-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app: kube-jwt-authn-webhook
spec:
  selector:
    app: kube-jwt-authn-webhook
  ports:
  - port: 3000
    targetPort: 3000
